# -*- coding: utf-8 -*-
"""sistemkelm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vp-cxa1GBbR9288sgO6rljlO6CZQkmmN
"""

import numpy as np
import pandas as pd
import pickle
import re
from sklearn.metrics import confusion_matrix

# =========================================================
#  FUNGSI KERNEL & KELM (TANPA NORMALISASI FITUR)
# =========================================================
def kernel_function(X1, X2, kernel_type='rbf', param=15.0):
    """
    Kernel function untuk KELM.
    - RBF: param = sigma
    """
    kernel_type = kernel_type.lower()

    if kernel_type == 'rbf':
        sigma = float(param)
        # ||X1 - X2||^2 = |X1|^2 + |X2|^2 - 2 X1.X2
        n1 = np.sum(X1**2, axis=1).reshape(-1, 1)  # (N1,1)
        n2 = np.sum(X2**2, axis=1).reshape(1, -1)  # (1,N2)
        D = n1 + n2 - 2 * (X1 @ X2.T)
        K = np.exp(-D / (2.0 * sigma**2))
        return K

    elif kernel_type == 'linear':
        return X1 @ X2.T

    elif kernel_type == 'polynomial':
        degree = int(param)
        gamma = 1.0
        coef0 = 1.0
        return (gamma * (X1 @ X2.T) + coef0) ** degree

    else:
        raise ValueError(f"Kernel '{kernel_type}' tidak didukung")


def kelm_train(X, T, kernel_type='rbf', kernel_param=15.0, C=100.0):
    """
    Training KELM:
    - X : (N, d) fitur train
    - T : (N, C) target one-hot
    """
    X = np.asarray(X, dtype=float)
    T = np.asarray(T, dtype=float)

    K = kernel_function(X, X, kernel_type, kernel_param)  # (N,N)
    N = K.shape[0]

    # beta = (K + I/C)^(-1) T
    beta = np.linalg.solve(K + np.eye(N) / C, T)

    model = {
        'X_train': X,
        'beta': beta,
        'kernel_type': kernel_type,
        'kernel_param': kernel_param,
        'C': C
    }
    return model


def kelm_predict(model, X):
    """
    Prediksi KELM:
    - model: dict dari kelm_train
    - X: fitur test (M,d)
    """
    X = np.asarray(X, dtype=float)

    Ktest = kernel_function(
        X,
        model['X_train'],
        model['kernel_type'],
        model['kernel_param']
    )
    Y = Ktest @ model['beta']  # (M,C)
    return Y


# =========================================================
#  EVALUASI METRIK (AKURASI, PRECISION MACRO, RECALL MACRO, F1 MACRO)
# =========================================================
def compute_macro_metrics(y_true, y_pred, class_names):
    """
    Hitung:
    - akurasi
    - precision macro
    - recall macro
    - F1-score macro
    Mirip dengan MATLAB versi kamu (rata-rata per kelas).
    """
    cm = confusion_matrix(y_true, y_pred, labels=class_names)
    cm = cm.astype(float)

    acc = np.trace(cm) / np.sum(cm)

    precision_list = []
    recall_list = []
    f1_list = []

    for i in range(len(class_names)):
        TP = cm[i, i]
        FP = np.sum(cm[:, i]) - TP
        FN = np.sum(cm[i, :]) - TP

        precision = TP / (TP + FP + 1e-12)
        recall = TP / (TP + FN + 1e-12)
        f1 = 2 * precision * recall / (precision + recall + 1e-12)

        precision_list.append(precision)
        recall_list.append(recall)
        f1_list.append(f1)

    precision_macro = np.mean(precision_list)
    recall_macro = np.mean(recall_list)
    f1_macro = np.mean(f1_list)

    return acc, precision_macro, recall_macro, f1_macro, cm


# =========================================================
#  MAIN SCRIPT: HANYA BEST MODEL (RBF, C=100, SIGMA=15, K=9)
# =========================================================
def main():
    # -------------------------------
    # 1. LOAD FITUR AVG_POOL DARI EXCEL
    # -------------------------------
    # Jika file ada di folder lain, boleh ganti dengan full path:
    # feat_file = r"C:\Users\fitri\Downloads\SKRIPSI\spesialis buah\DATA TAKBIR\ResNet50_AvgPool_AllDataFIXmurni.xlsx"
    feat_file = 'ResNet50_AvgPool_AllDataFIXmurni.xlsx'
    sheet_feat = 'AllData'

    print(f"\n▶ Memuat fitur dari file: {feat_file} (sheet: {sheet_feat})")
    df_feat = pd.read_excel(feat_file, sheet_name=sheet_feat)

    # Asumsi kolom: Index, Filename, Label, F1..Fd, dst.
    # Label -> string, lalu kategori
    labels_all = df_feat['Label'].astype(str)
    class_names = np.sort(labels_all.unique())
    num_classes = len(class_names)

    # Ambil kolom fitur F1..Fd dengan pola F + angka (regex '^F[0-9]+$')
    feature_cols = [
        c for c in df_feat.columns
        if re.match(r'^F[0-9]+$', str(c))  # <<< PERBAIKAN DI SINI
    ]
    if len(feature_cols) == 0:
        raise ValueError("Tidak ditemukan kolom fitur dengan pola nama 'F1', 'F2', ..., cek header Excel.")

    X_all = df_feat[feature_cols].values.astype(float)
    num_samples, feat_dim = X_all.shape

    print(f"✔ Fitur & label dimuat. N sampel = {num_samples}, dimensi fitur = {feat_dim}")
    print("  Kelas:", class_names)

    # -------------------------------
    # 2. LOAD SPLIT K=9 DARI EXCEL
    # -------------------------------
    # Jika file ada di folder lain, ganti dengan full path juga:
    # split_file = r"C:\Users\fitri\Downloads\SKRIPSI\spesialis buah\DATA TAKBIR\KFold_Splits_K5to10FIX.xlsx"
    split_file = 'KFold_Splits_K5to10FIX.xlsx'
    sheet_split = 'K9'
    print(f"\n▶ Memuat pembagian K-Fold K=9 dari file: {split_file} (sheet: {sheet_split})")

    df_split = pd.read_excel(split_file, sheet_name=sheet_split)

    # Asumsi ada kolom: Index, Fold, Set
    # Index di Excel / MATLAB biasanya 1..N → di Python 0..N-1, jadi dikurangi 1
    idx_excel = df_split['Index'].astype(int).values
    idx_py = idx_excel - 1
    df_split['Index_py'] = idx_py

    k_fold = 9
    print("✔ Split K=9 dimuat.")

    # -------------------------------
    # 3. PARAMETER BEST MODEL
    # -------------------------------
    kernel_type = 'rbf'
    C_value = 100.0
    sigma_rbf = 15.0

    print("\n============================================")
    print(f"  Evaluasi KELM Best Model")
    print(f"  Kernel    : {kernel_type.upper()}")
    print(f"  C         : {C_value}")
    print(f"  Sigma RBF : {sigma_rbf}")
    print(f"  K-Fold    : {k_fold}")
    print("============================================\n")

    # -------------------------------
    # 4. LOOP FOLD K=9
    # -------------------------------
    results = []
    cm_total = np.zeros((num_classes, num_classes), dtype=float)

    # mapping label -> index (dipakai berulang)
    class_to_idx = {c: i for i, c in enumerate(class_names)}

    for fold in range(1, k_fold + 1):
        print(f">> Fold {fold}/{k_fold}")

        mask_fold = df_split['Fold'] == fold
        set_str = df_split['Set'].astype(str)

        train_mask = mask_fold & (set_str == 'Train')
        test_mask = mask_fold & (set_str == 'Test')

        train_index_py = df_split.loc[train_mask, 'Index_py'].values
        test_index_py = df_split.loc[test_mask, 'Index_py'].values

        # Ambil data train/test (ingat Index_py sudah 0-based)
        X_train = X_all[train_index_py, :]
        X_test = X_all[test_index_py, :]

        y_train = labels_all.iloc[train_index_py].astype(str).values
        y_test = labels_all.iloc[test_index_py].astype(str).values

        # One-hot target (urutan class_names)
        T_train = np.zeros((len(y_train), num_classes), dtype=float)
        for i, lab in enumerate(y_train):
            T_train[i, class_to_idx[lab]] = 1.0

        # ----- TRAIN KELM TANPA NORMALISASI -----
        model_fold = kelm_train(
            X_train,
            T_train,
            kernel_type=kernel_type,
            kernel_param=sigma_rbf,
            C=C_value
        )

        # ----- PREDIKSI -----
        Y_pred_score = kelm_predict(model_fold, X_test)
        y_pred_idx = np.argmax(Y_pred_score, axis=1)
        y_pred = np.array([class_names[i] for i in y_pred_idx])

        # ----- METRIK -----
        acc, prec_macro, rec_macro, f1_macro, cm = compute_macro_metrics(
            y_test, y_pred, class_names
        )
        cm_total += cm

        print(f"   Akurasi Fold      : {acc * 100:.2f}%")
        print(f"   Precision (macro) : {prec_macro * 100:.2f}%")
        print(f"   Recall (macro)    : {rec_macro * 100:.2f}%")
        print(f"   F1-score (macro)  : {f1_macro * 100:.2f}%")

        results.append({
            'Fold': fold,
            'Akurasi(%)': acc * 100.0,
            'Precision_Macro(%)': prec_macro * 100.0,
            'Recall_Macro(%)': rec_macro * 100.0,
            'F1_Macro(%)': f1_macro * 100.0
        })

    # -------------------------------
    # 5. REKAP RATA-RATA K=9
    # -------------------------------
    df_results = pd.DataFrame(results)
    avg_row = {
        'Fold': 'Rata-rata',
        'Akurasi(%)': df_results['Akurasi(%)'].mean(),
        'Precision_Macro(%)': df_results['Precision_Macro(%)'].mean(),
        'Recall_Macro(%)': df_results['Recall_Macro(%)'].mean(),
        'F1_Macro(%)': df_results['F1_Macro(%)'].mean()
    }
    df_results = pd.concat([df_results, pd.DataFrame([avg_row])], ignore_index=True)

    print("\n>>> Rekap Rata-rata (K=9) <<<")
    print(df_results.tail(1))

    # Confusion matrix total
    cm_total_df = pd.DataFrame(cm_total, index=class_names, columns=class_names)

    # -------------------------------
    # 6. SIMPAN HASIL EVALUASI KE EXCEL
    # -------------------------------
    eval_file = 'hasil_bestmodelsistemkelm.xlsx'
    with pd.ExcelWriter(eval_file) as writer:
        df_results.to_excel(writer, sheet_name='BestModel_K9', index=False)
        cm_total_df.to_excel(writer, sheet_name='ConfusionMatrix_Total')

    print(f"\n✔ Hasil evaluasi best model tersimpan di: {eval_file}")

    # -------------------------------
    # 7. LATIH ULANG BEST MODEL DI SELURUH DATA & SIMPAN
    # -------------------------------
    print("\n▶ Melatih ulang KELM Best Model di SELURUH data...")

    # One-hot seluruh data
    T_all = np.zeros((num_samples, num_classes), dtype=float)
    for i, lab in enumerate(labels_all.astype(str).values):
        T_all[i, class_to_idx[lab]] = 1.0

    best_model_all = kelm_train(
        X_all,
        T_all,
        kernel_type=kernel_type,
        kernel_param=sigma_rbf,
        C=C_value
    )

    # Simpan info tambahan
    best_model_all['class_names'] = class_names
    best_model_all['feat_file'] = feat_file
    best_model_all['split_file'] = split_file
    best_model_all['k_fold'] = k_fold

    model_file = 'KELM_BestModel_RBF_C100_sigma15.pkl'
    with open(model_file, 'wb') as f:
        pickle.dump(best_model_all, f)

    print(f"✔ Model terbaik disimpan ke file: {model_file}")
    print("  (Untuk load kembali gunakan:  pickle.load(open('{model_file}', 'rb')) )")


if __name__ == '__main__':
    main()